#!/usr/bin/env bash
# Create a release of wald
#
# Usage:
#   ./release.sh 0.2.0                    # Full release (all platforms)
#   ./release.sh --dry-run 0.2.0          # Show what would happen
#   ./release.sh --platform native 0.2.0  # Only current platform
#   ./release.sh --skip-bump 0.2.0        # Skip version bump (if already done)
#   ./release.sh --no-push 0.2.0          # Don't push to remote
#   ./release.sh --no-gitlab-release 0.2.0  # Skip GitLab release creation
#
# This script:
# 1. Bumps version (via bump-version.sh) if not skipped
# 2. Cleans previous build artifacts
# 3. Builds for all platforms
# 4. Generates SHA256 checksums
# 5. Creates git tag
# 6. Pushes to remote (commit + tag)
# 7. Creates GitLab release with artifacts

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Defaults
DRY_RUN=false
SKIP_BUMP=false
NO_PUSH=false
NO_GITLAB_RELEASE=false
PLATFORMS="all"

# Parse arguments
while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run|-n)
      DRY_RUN=true
      shift
      ;;
    --skip-bump)
      SKIP_BUMP=true
      shift
      ;;
    --no-push)
      NO_PUSH=true
      shift
      ;;
    --no-gitlab-release)
      NO_GITLAB_RELEASE=true
      shift
      ;;
    --platform)
      PLATFORMS="$2"
      shift 2
      ;;
    -h|--help)
      head -18 "$0" | tail -15
      exit 0
      ;;
    *)
      VERSION="$1"
      shift
      ;;
  esac
done

if [[ -z "${VERSION:-}" ]]; then
  echo "Usage: $0 [options] <version>" >&2
  echo "Run '$0 --help' for options" >&2
  exit 1
fi

# Validate version format
if ! [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[A-Za-z0-9.]+)?$ ]]; then
  echo "Error: Invalid version format: $VERSION" >&2
  exit 1
fi

# Validate branch (releases only from main)
CURRENT_BRANCH=$(git -C "$REPO_ROOT" branch --show-current)
if [[ "$CURRENT_BRANCH" != "main" ]]; then
  echo "Error: Releases must be made from main branch (currently on: $CURRENT_BRANCH)" >&2
  exit 1
fi

echo "=== wald Release $VERSION ==="
echo ""

if [[ "$DRY_RUN" == "true" ]]; then
  echo "[DRY RUN MODE - no changes will be made]"
  echo ""
fi

# ============================================================================
# Step 1: Version bump
# ============================================================================

if [[ "$SKIP_BUMP" == "false" ]]; then
  echo "Step 1: Bumping version..."

  CURRENT_VERSION=$(cat "$REPO_ROOT/VERSION" | tr -d '\n')
  if [[ "$CURRENT_VERSION" == "$VERSION" ]]; then
    echo "  Version already at $VERSION, skipping bump"
  else
    if [[ "$DRY_RUN" == "true" ]]; then
      echo "  Would run: ./bump-version.sh $VERSION"
    else
      "$REPO_ROOT/bump-version.sh" "$VERSION"
    fi
  fi
else
  echo "Step 1: Skipping version bump (--skip-bump)"
fi

echo ""

# ============================================================================
# Step 2: Clean previous build artifacts
# ============================================================================

echo "Step 2: Cleaning previous build artifacts..."

if [[ "$DRY_RUN" == "true" ]]; then
  echo "  Would run: ./clean.sh"
else
  "$REPO_ROOT/clean.sh"
fi

echo ""

# ============================================================================
# Step 3: Build for all platforms
# ============================================================================

echo "Step 3: Building for platforms: $PLATFORMS..."

if [[ "$DRY_RUN" == "true" ]]; then
  echo "  Would run: ./build-all.sh --platform $PLATFORMS --checksums"
else
  "$REPO_ROOT/build-all.sh" --platform "$PLATFORMS" --checksums
fi

echo ""

# ============================================================================
# Step 4: Generate checksums (done by build-all.sh --checksums)
# ============================================================================

echo "Step 4: Checksums generated by build-all.sh"
CHECKSUM_FILE="$REPO_ROOT/build/checksums-$VERSION.txt"

echo ""

# ============================================================================
# Step 5: Create git tag
# ============================================================================

echo "Step 5: Creating git tag v$VERSION..."

if [[ "$DRY_RUN" == "true" ]]; then
  echo "  Would run: git tag -a v$VERSION -m 'Release v$VERSION'"
else
  if git -C "$REPO_ROOT" tag | grep -q "^v$VERSION$"; then
    echo "  Tag v$VERSION already exists, skipping"
  else
    git -C "$REPO_ROOT" tag -a "v$VERSION" -m "Release v$VERSION"
    echo "  Created annotated tag: v$VERSION"
  fi
fi

echo ""

# ============================================================================
# Step 6: Push to remote
# ============================================================================

if [[ "$NO_PUSH" == "false" ]]; then
  echo "Step 6: Pushing to remote..."

  if [[ "$DRY_RUN" == "true" ]]; then
    echo "  Would run: git push origin && git push origin --tags"
  else
    echo "  Pushing to GitLab (origin)..."
    git -C "$REPO_ROOT" push origin
    git -C "$REPO_ROOT" push origin --tags
    echo "  Pushed to origin"
  fi
else
  echo "Step 6: Skipping push (--no-push)"
fi

echo ""

# ============================================================================
# Step 7: Create GitLab release with artifacts
# ============================================================================

if [[ "$NO_GITLAB_RELEASE" == "false" && "$NO_PUSH" == "false" ]]; then
  echo "Step 7: Creating GitLab release..."

  # Extract project path from remote URL (strip .git suffix if present)
  REMOTE_URL=$(git -C "$REPO_ROOT" remote get-url origin 2>/dev/null || echo "")
  if [[ "$REMOTE_URL" =~ git\.zib\.de[:/](.+)$ ]]; then
    PROJECT_PATH="${BASH_REMATCH[1]%.git}"
  else
    echo "  Error: Could not parse GitLab project path from remote URL" >&2
    echo "  Remote URL: $REMOTE_URL" >&2
    exit 1
  fi

  if [[ "$DRY_RUN" == "true" ]]; then
    echo "  Would run: glab release create v$VERSION --repo $PROJECT_PATH ..."
    echo "  Would attach:"
    find "$REPO_ROOT/build" -type f \( -name "wald-*-$VERSION" -o -name "checksums-$VERSION*" \) 2>/dev/null | sort | while read -r f; do
      echo "    - $(basename "$f")"
    done
  else
    # Collect all artifacts
    ARTIFACTS=()
    while IFS= read -r -d '' f; do
      ARTIFACTS+=("$f")
    done < <(find "$REPO_ROOT/build" -type f \( -name "wald-*-$VERSION" -o -name "checksums-$VERSION*" \) -print0 2>/dev/null | sort -z)

    if [[ ${#ARTIFACTS[@]} -eq 0 ]]; then
      echo "  Warning: No artifacts found in build/"
    else
      echo "  Uploading ${#ARTIFACTS[@]} artifacts..."
      glab release create "v$VERSION" \
        --name "v$VERSION" \
        --notes "Release v$VERSION" \
        --repo "$PROJECT_PATH" \
        "${ARTIFACTS[@]}"
      echo "  Created release: v$VERSION"
    fi
  fi
else
  echo "Step 7: Skipping GitLab release (--no-gitlab-release or --no-push)"
fi

echo ""

# ============================================================================
# Summary
# ============================================================================

echo "=== Release Summary ==="
echo ""
echo "Version: $VERSION"
echo "Tag: v$VERSION"
echo ""
echo "Artifacts:"
find "$REPO_ROOT/build" -type f -name "wald-*-$VERSION" -exec ls -lh {} \; 2>/dev/null | sort | while read -r line; do
  echo "  $line"
done
echo ""
echo "Checksums: $CHECKSUM_FILE"
echo ""

if [[ -n "${PROJECT_PATH:-}" ]]; then
  echo "GitLab Release: https://git.zib.de/$PROJECT_PATH/-/releases/v$VERSION"
fi
echo ""

if [[ "$DRY_RUN" == "true" ]]; then
  echo "[DRY RUN COMPLETE - no changes were made]"
else
  echo "Release v$VERSION complete!"
fi
