#!/usr/bin/env bash
# Create a release of wald
#
# Usage:
#   ./release.sh                          # Dev release (default, current platform)
#   ./release.sh --dev                    # Explicit dev release
#   ./release.sh 0.2.0                    # Full release (all platforms)
#   ./release.sh --dry-run 0.2.0          # Show what would happen
#   ./release.sh --platform native 0.2.0  # Only current platform
#   ./release.sh --platform all 0.2.0     # All platforms
#   ./release.sh --skip-bump 0.2.0        # Skip version bump (if already done)
#   ./release.sh --no-push 0.2.0          # Don't push to remote
#   ./release.sh --no-gitlab-release 0.2.0  # Skip GitLab release creation
#
# Dev releases:
# - Build current platform only (use --platform all for cross-compile)
# - No version bump, no git tag, no git push
# - Creates/updates GitLab release tagged "dev"
#
# Full releases:
# - Bump version, build all platforms, create git tag, push, create GitLab release

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Defaults
DEV_RELEASE=false
DRY_RUN=false
SKIP_BUMP=false
NO_PUSH=false
NO_GITLAB_RELEASE=false
PLATFORMS=""  # Will be set based on dev/full release

# Parse arguments
while [[ $# -gt 0 ]]; do
  case "$1" in
    --dev)
      DEV_RELEASE=true
      shift
      ;;
    --dry-run|-n)
      DRY_RUN=true
      shift
      ;;
    --skip-bump)
      SKIP_BUMP=true
      shift
      ;;
    --no-push)
      NO_PUSH=true
      shift
      ;;
    --no-gitlab-release)
      NO_GITLAB_RELEASE=true
      shift
      ;;
    --platform)
      PLATFORMS="$2"
      shift 2
      ;;
    -h|--help)
      head -22 "$0" | tail -19
      exit 0
      ;;
    *)
      VERSION="$1"
      shift
      ;;
  esac
done

# Default to dev release if no version specified
if [[ -z "${VERSION:-}" ]]; then
  DEV_RELEASE=true
fi

# Set defaults based on release type
if [[ "$DEV_RELEASE" == "true" ]]; then
  BASE_VERSION=$(cat "$REPO_ROOT/VERSION" | tr -d '\n')
  VERSION="${BASE_VERSION}-dev"
  ARTIFACT_VERSION="dev"            # Artifacts use "dev" for dev releases
  SKIP_BUMP=true
  NO_PUSH=true
  # darwin-amd64 cross-compile requires x86_64 OpenSSL, skip for now
  PLATFORMS="${PLATFORMS:-darwin-arm64,linux-amd64,linux-arm64}"
else
  ARTIFACT_VERSION="$VERSION"       # For full releases, artifacts match version
  PLATFORMS="${PLATFORMS:-all}"     # Default to all for full release

  # Validate version format for full releases
  if ! [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[A-Za-z0-9.]+)?$ ]]; then
    echo "Error: Invalid version format: $VERSION" >&2
    exit 1
  fi

  # Validate branch (full releases only from main)
  CURRENT_BRANCH=$(git -C "$REPO_ROOT" branch --show-current)
  if [[ "$CURRENT_BRANCH" != "main" ]]; then
    echo "Error: Releases must be made from main branch (currently on: $CURRENT_BRANCH)" >&2
    exit 1
  fi
fi

if [[ "$DEV_RELEASE" == "true" ]]; then
  echo "=== wald Dev Release $VERSION ==="
else
  echo "=== wald Release $VERSION ==="
fi
echo ""

if [[ "$DRY_RUN" == "true" ]]; then
  echo "[DRY RUN MODE - no changes will be made]"
  echo ""
fi

# ============================================================================
# Step 1: Version bump
# ============================================================================

if [[ "$SKIP_BUMP" == "false" ]]; then
  echo "Step 1: Bumping version..."

  CURRENT_VERSION=$(cat "$REPO_ROOT/VERSION" | tr -d '\n')
  if [[ "$CURRENT_VERSION" == "$VERSION" ]]; then
    echo "  Version already at $VERSION, skipping bump"
  else
    if [[ "$DRY_RUN" == "true" ]]; then
      echo "  Would run: ./bump-version.sh $VERSION"
    else
      "$REPO_ROOT/bump-version.sh" "$VERSION"
    fi
  fi
else
  echo "Step 1: Skipping version bump (--skip-bump)"
fi

echo ""

# ============================================================================
# Step 2: Clean previous build artifacts
# ============================================================================

echo "Step 2: Cleaning previous build artifacts..."

if [[ "$DRY_RUN" == "true" ]]; then
  echo "  Would run: ./clean.sh"
else
  "$REPO_ROOT/clean.sh"
fi

echo ""

# ============================================================================
# Step 3: Build for all platforms
# ============================================================================

echo "Step 3: Building for platforms: $PLATFORMS..."

if [[ "$DRY_RUN" == "true" ]]; then
  echo "  Would run: ./build-all.sh --platform $PLATFORMS --version $ARTIFACT_VERSION --checksums"
else
  "$REPO_ROOT/build-all.sh" --platform "$PLATFORMS" --version "$ARTIFACT_VERSION" --checksums
fi

echo ""

# ============================================================================
# Step 4: Generate checksums (done by build-all.sh --checksums)
# ============================================================================

echo "Step 4: Checksums generated by build-all.sh"
CHECKSUM_FILE="$REPO_ROOT/build/checksums-$ARTIFACT_VERSION.txt"

echo ""

# ============================================================================
# Step 5: Create git tag (skip for dev releases)
# ============================================================================

if [[ "$DEV_RELEASE" == "true" ]]; then
  echo "Step 5: Skipping git tag (dev release)"
else
  echo "Step 5: Creating git tag v$VERSION..."

  if [[ "$DRY_RUN" == "true" ]]; then
    echo "  Would run: git tag -a v$VERSION -m 'Release v$VERSION'"
  else
    if git -C "$REPO_ROOT" tag | grep -q "^v$VERSION$"; then
      echo "  Tag v$VERSION already exists, skipping"
    else
      git -C "$REPO_ROOT" tag -a "v$VERSION" -m "Release v$VERSION"
      echo "  Created annotated tag: v$VERSION"
    fi
  fi
fi

echo ""

# ============================================================================
# Step 6: Push to remote
# ============================================================================

if [[ "$NO_PUSH" == "false" ]]; then
  echo "Step 6: Pushing to remote..."

  if [[ "$DRY_RUN" == "true" ]]; then
    echo "  Would run: git push origin && git push origin --tags"
  else
    echo "  Pushing to GitLab (origin)..."
    git -C "$REPO_ROOT" push origin
    git -C "$REPO_ROOT" push origin --tags
    echo "  Pushed to origin"
  fi
else
  echo "Step 6: Skipping push (--no-push)"
fi

echo ""

# ============================================================================
# Step 7: Create GitLab release with artifacts
# ============================================================================

# For dev releases, we create GitLab release even without git push
SHOULD_CREATE_RELEASE=false
if [[ "$NO_GITLAB_RELEASE" == "false" ]]; then
  if [[ "$DEV_RELEASE" == "true" ]]; then
    SHOULD_CREATE_RELEASE=true
  elif [[ "$NO_PUSH" == "false" ]]; then
    SHOULD_CREATE_RELEASE=true
  fi
fi

if [[ "$SHOULD_CREATE_RELEASE" == "true" ]]; then
  echo "Step 7: Creating GitLab release..."

  # Extract project path from remote URL (strip .git suffix if present)
  REMOTE_URL=$(git -C "$REPO_ROOT" remote get-url origin 2>/dev/null || echo "")
  if [[ "$REMOTE_URL" =~ git\.zib\.de[:/](.+)$ ]]; then
    PROJECT_PATH="${BASH_REMATCH[1]%.git}"
  else
    echo "  Error: Could not parse GitLab project path from remote URL" >&2
    echo "  Remote URL: $REMOTE_URL" >&2
    exit 1
  fi

  # Collect all artifacts
  ARTIFACTS=()
  while IFS= read -r -d '' f; do
    ARTIFACTS+=("$f")
  done < <(find "$REPO_ROOT/build" -type f \( -name "wald-*-$ARTIFACT_VERSION" -o -name "checksums-$ARTIFACT_VERSION*" \) -print0 2>/dev/null | sort -z)

  if [[ "$DRY_RUN" == "true" ]]; then
    if [[ "$DEV_RELEASE" == "true" ]]; then
      echo "  Would delete existing dev release (if any)"
      echo "  Would run: glab release create dev --ref main --repo $PROJECT_PATH ..."
    else
      echo "  Would run: glab release create v$VERSION --repo $PROJECT_PATH ..."
    fi
    echo "  Would attach:"
    for f in "${ARTIFACTS[@]}"; do
      echo "    - $(basename "$f")"
    done
  else
    if [[ ${#ARTIFACTS[@]} -eq 0 ]]; then
      echo "  Warning: No artifacts found in build/"
    else
      if [[ "$DEV_RELEASE" == "true" ]]; then
        # Delete existing dev release if it exists
        echo "  Deleting existing dev release (if any)..."
        glab release delete dev --repo "$PROJECT_PATH" --yes 2>/dev/null || true

        HEAD_HASH=$(git -C "$REPO_ROOT" rev-parse --short HEAD)
        HEAD_HASH_FULL=$(git -C "$REPO_ROOT" rev-parse HEAD)

        echo "  Uploading ${#ARTIFACTS[@]} artifacts..."
        glab release create dev \
          --name "Development Build" \
          --notes "Development build from main branch

**Commit:** [\`$HEAD_HASH\`](https://git.zib.de/$PROJECT_PATH/-/commit/$HEAD_HASH_FULL)
**Date:** $(date -u +%Y-%m-%d' '%H:%M' UTC')" \
          --ref main \
          --repo "$PROJECT_PATH" \
          "${ARTIFACTS[@]}"
        echo "  Created dev release"
      else
        echo "  Uploading ${#ARTIFACTS[@]} artifacts..."
        glab release create "v$VERSION" \
          --name "v$VERSION" \
          --notes "Release v$VERSION" \
          --repo "$PROJECT_PATH" \
          "${ARTIFACTS[@]}"
        echo "  Created release: v$VERSION"
      fi
    fi
  fi
else
  echo "Step 7: Skipping GitLab release (--no-gitlab-release)"
fi

echo ""

# ============================================================================
# Summary
# ============================================================================

echo "=== Release Summary ==="
echo ""
echo "Version: $VERSION"
if [[ "$DEV_RELEASE" == "true" ]]; then
  echo "Type: Development release"
else
  echo "Tag: v$VERSION"
fi
echo ""
echo "Artifacts:"
find "$REPO_ROOT/build" -type f -name "wald-*-$ARTIFACT_VERSION" -exec ls -lh {} \; 2>/dev/null | sort | while read -r line; do
  echo "  $line"
done
echo ""
echo "Checksums: $CHECKSUM_FILE"
echo ""

if [[ -n "${PROJECT_PATH:-}" ]]; then
  if [[ "$DEV_RELEASE" == "true" ]]; then
    echo "GitLab Release: https://git.zib.de/$PROJECT_PATH/-/releases/dev"
  else
    echo "GitLab Release: https://git.zib.de/$PROJECT_PATH/-/releases/v$VERSION"
  fi
fi
echo ""

if [[ "$DRY_RUN" == "true" ]]; then
  echo "[DRY RUN COMPLETE - no changes were made]"
elif [[ "$DEV_RELEASE" == "true" ]]; then
  echo "Dev release complete!"
else
  echo "Release v$VERSION complete!"
fi
